from flask import Flask
from flask_cors import CORS

from pbp_situation_model import train_pbp_model, predict_play
from run_model import train_run_models, predict_run_metrics


app = Flask(__name__)
CORS(app, resources={r"/*": {"origins": "*"}})


@app.route("/suggestPlay/<situation>", methods=['GET'])
def suggest_play(situation):
    ''' Endpoint from the React frontend to get play suggestion based on the incoming situation '''

    # Convert the attributes from the URL string to a list of appropriate types
    '''
        The string is as follows:

        "down [0], ydstogo [1], yardline_100 [2], goal_to_go [3], quarter_seconds_remaining [4], half_seconds_remaining [5], 
        game_seconds_remaining [6], score_differential [7], posteam_timeouts_remaining [8], defteam_timeouts_remaining [9], 
        posteam [10], defteam [11]"
    '''
    situation = situation.split(',')
    situation = [int(situation[0]), int(situation[1]), int(situation[2]), int(situation[3]), int(situation[4]),
                 int(situation[5]), int(situation[6]), int(situation[7]), int(situation[8]), int(situation[9]),
                 situation[10], situation[11]]

    # Predict whether the play type for the given situation should be a run or pass
    prediction, confidence = predict_play(situation, trained_model=train_pbp_model()[0], feature_columns=train_pbp_model()[1])

    # Depending on the prediction, feed it into the run or pass model
    if prediction == 'run':
        run_prediction = predict_run_metrics(situation, trained_models=train_run_models())
        print(f"Run Prediction: {run_prediction}")





    # PLACEHOLDER RETURN STATEMENT
    # END GOAL IS TO RETURN A VISUALIZATION OF THE ROUTE GENERATED BY MATPLOTLIB
    return f"Prediction: {prediction} with confidence {confidence}"


if __name__ == "__main__":
    app.run()