from pbp_situation_model import train_pbp_model, predict_play
from flask import Flask
from flask_cors import CORS


app = Flask(__name__)
CORS(app, resources={r"/*": {"origins": "*"}})


@app.route("/suggestPlay/<situation>", methods=['GET'])
def suggest_play(situation):
    ''' Endpoint from the React frontend to get play suggestion based on the incoming situation '''

    # Convert the attributes from the URL string to a list of appropriate types
    '''[down, ydstogo, yardline_100, goal_to_go, quarter_seconds_remaining, half_seconds_remaining, game_seconds_remaining, 
    score_differential, wp, ep, posteam_timeouts_remaining, defteam_timeouts_remaining, posteam, defteam]'''
    situation = situation.split(',')
    situation = [int(situation[0]), int(situation[1]), int(situation[2]), int(situation[3]), int(situation[4]),
                 int(situation[5]), int(situation[6]), int(situation[7]), float(situation[8]), float(situation[9]),
                 int(situation[10]), int(situation[11]), situation[12], situation[13]]


    # Calculate the win probability (wp) and expected points (ep) for the incoming situation
    ''' logic goes here '''

    # Train the PBP Situation Model
    trained_model, feature_columns = train_pbp_model()
    print(feature_columns)
    print()

    # Predict whether the play type for the given situation should be a run or pass
    prediction, confidence = predict_play(situation, trained_model, feature_columns)

    # PLACEHOLDER RETURN STATEMENT
    # END GOAL IS TO RETURN A VISUALIZATION OF THE ROUTE GENERATED BY MATPLOTLIB
    return f"Prediction: {prediction} with confidence {confidence}"


if __name__ == "__main__":
    app.run()